import { Fragment, type ReactNode } from "react";

interface CodeBlockProps {
  /** Heading is the wrapper aria-label; the visual heading lives outside. */
  ariaLabel?: string;
  /**
   * "sql"   — tiny token-based SQL highlighter.
   * "call"  — engine-call shape (`fn(\n  arg = value,\n)`); colours the
   *           function name, argument names, and literal values.
   * "plain" — passes through.
   */
  language?: "sql" | "call" | "plain";
  children: ReactNode;
}

export function CodeBlock({ ariaLabel, language = "plain", children }: CodeBlockProps) {
  const body =
    typeof children !== "string"
      ? children
      : language === "sql"
        ? highlightSql(children)
        : language === "call"
          ? highlightCall(children)
          : children;
  return (
    <pre
      aria-label={ariaLabel}
      className="t-mono text-sm leading-relaxed whitespace-pre-wrap rounded-md border border-border bg-surface-inverted text-surface px-lg py-md overflow-x-auto"
    >
      {body}
    </pre>
  );
}

// Tiny SQL highlighter: keyword / string / number / comment / identifier.
// Order matters: comments + strings first so keywords inside them don't match.
const SQL_KEYWORDS = new Set([
  "SELECT",
  "FROM",
  "WHERE",
  "AND",
  "OR",
  "NOT",
  "IN",
  "IS",
  "NULL",
  "GROUP",
  "BY",
  "ORDER",
  "HAVING",
  "LIMIT",
  "OFFSET",
  "JOIN",
  "LEFT",
  "RIGHT",
  "INNER",
  "OUTER",
  "ON",
  "AS",
  "DISTINCT",
  "UNION",
  "ALL",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "WITH",
  "BETWEEN",
  "LIKE",
  "ILIKE",
  "ASC",
  "DESC",
  "TRUE",
  "FALSE",
  "INTERVAL",
  "COUNT",
  "SUM",
  "AVG",
  "MIN",
  "MAX",
  "ROUND",
  "COALESCE",
  "DATE_TRUNC",
  "EXTRACT",
  "NOW",
  "CURRENT_DATE",
]);

// Single pass: comment | string | number | identifier-or-keyword | other
const SQL_TOKEN = /(--[^\n]*|\/\*[\s\S]*?\*\/)|('(?:[^']|'')*')|(\b\d+(?:\.\d+)?\b)|(\b[A-Za-z_][A-Za-z0-9_]*\b)|([\s\S])/g;

// Engine-call shape, generated by `renderFunctionCall`:
//   tool_name(
//     arg = "string",
//     arg2 = 5,
//     arg3 = null,
//   )
// Line-based since the producer is deterministic — no need for a full
// tokenizer with state.
const CALL_ARG_LINE = /^(\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*=\s*)(.*?)(,?)$/;
const CALL_FUNC_LINE = /^([A-Za-z_][A-Za-z0-9_]*)(.*)$/;

function highlightCall(src: string): ReactNode {
  const lines = src.split("\n");
  const out: ReactNode[] = [];
  let key = 0;
  lines.forEach((line, idx) => {
    if (idx > 0) out.push("\n");
    if (idx === 0) {
      const m = CALL_FUNC_LINE.exec(line);
      if (m !== null) {
        out.push(
          <span
            key={key++}
            className="font-medium"
            style={{ color: "var(--accent-default)" }}
          >
            {m[1]}
          </span>,
        );
        out.push(m[2] ?? "");
      } else {
        out.push(line);
      }
      return;
    }
    const m = CALL_ARG_LINE.exec(line);
    if (m === null) {
      out.push(line);
      return;
    }
    out.push(m[1] ?? "");
    out.push(
      <span key={key++} style={{ color: "var(--text-secondary)" }}>
        {m[2]}
      </span>,
    );
    out.push(m[3] ?? "");
    out.push(highlightCallValue(m[4] ?? "", key++));
    if (m[5] !== undefined && m[5] !== "") out.push(m[5]);
  });
  return <>{out}</>;
}

function highlightCallValue(v: string, key: number): ReactNode {
  if (v.startsWith('"') || v.startsWith("'")) {
    return (
      <span key={key} style={{ color: "var(--signal-positive)" }}>
        {v}
      </span>
    );
  }
  if (/^-?\d/.test(v)) {
    return (
      <span key={key} style={{ color: "var(--signal-warning)" }}>
        {v}
      </span>
    );
  }
  if (v === "true" || v === "false" || v === "null" || v === "undefined") {
    return (
      <span key={key} style={{ color: "var(--text-tertiary)" }}>
        {v}
      </span>
    );
  }
  return v;
}


function highlightSql(src: string): ReactNode {
  const nodes: ReactNode[] = [];
  let key = 0;
  let plain = "";
  function flushPlain() {
    if (plain.length > 0) {
      nodes.push(plain);
      plain = "";
    }
  }
  for (const m of src.matchAll(SQL_TOKEN)) {
    const [, comment, str, num, ident, other] = m;
    if (comment !== undefined) {
      flushPlain();
      nodes.push(
        <span key={key++} className="text-text-tertiary italic">
          {comment}
        </span>,
      );
    } else if (str !== undefined) {
      flushPlain();
      nodes.push(
        <span key={key++} style={{ color: "var(--signal-positive)" }}>
          {str}
        </span>,
      );
    } else if (num !== undefined) {
      flushPlain();
      nodes.push(
        <span key={key++} style={{ color: "var(--signal-warning)" }}>
          {num}
        </span>,
      );
    } else if (ident !== undefined) {
      if (SQL_KEYWORDS.has(ident.toUpperCase())) {
        flushPlain();
        nodes.push(
          <span key={key++} className="font-medium" style={{ color: "var(--accent-default)" }}>
            {ident}
          </span>,
        );
      } else {
        plain += ident;
      }
    } else if (other !== undefined) {
      plain += other;
    }
  }
  flushPlain();
  return (
    <>
      {nodes.map((n, i) => (
        <Fragment key={i}>{n}</Fragment>
      ))}
    </>
  );
}
